//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Budget.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int Id { get; set; }
        public int IdAccount { get; set; }
        public int IdOperationType { get; set; }
        public decimal Ammount { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual OperationType OperationType { get; set; }
    }
}
